name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
{% if cookiecutter.project_add_default_packages == "yes" %}
  - black
  - invoke
  - jupyter
  - jupyterlab
  - keras
  - lightgbm
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
{% elif cookiecutter.project_add_default_packages == "no" %}
{% endif %}
  - pip
{% if cookiecutter.project_add_default_packages == "yes" %}
  - plotly
  - pyjanitor
  - pylint
  - pyspark
{% elif cookiecutter.project_add_default_packages == "no" %}
{% endif %}
  - python={{ cookiecutter.python_version }}
{% if cookiecutter.project_add_default_packages == "yes" %}
  - python-dotenv
  - scikit-learn
  - seaborn
  - statsmodels
  - tensorflow
{% elif cookiecutter.project_add_default_packages == "no" %}
{% endif %}
  - pip:
{% if cookiecutter.project_add_default_packages == "yes" %}
    - h2o
{% elif cookiecutter.project_add_default_packages == "no" %}
{% endif %}
    - pyhere