name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  {%- if cookiecutter.project_add_default_packages == "yes" -%}
  - black
  {%- if cookiecutter.project_add_default_packages == "yes" -%}
  - invoke
  - jupyter
  - jupyterlab
  {% endif %}
  - keras
  - lightgbm
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
  {% endif %}
  - pip
  {%- if cookiecutter.project_add_default_packages == "yes" -%}
  - plotly
  - pyjanitor
  - pylint
  - pyspark
  {% endif %}
  - python={{ cookiecutter.python_version }}
  {%- if cookiecutter.project_add_default_packages == "yes" -%}
  - python-dotenv
  - scikit-learn
  - seaborn
  - statsmodels
  - tensorflow
  {% endif %}
  - pip:
  {%- if cookiecutter.project_add_default_packages == "yes" -%}
    - h2o
  {% endif %}
    - pyhere