name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
{% if cookiecutter.project_add_default_packages == "Yes"}
  - black
  - invoke
  - jupyter
  - jupyterlab
  - keras
  - lightgbm
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
  - pip
  - plotly
  - pyjanitor
  - pylint
  - pyspark
{% endif %}
  - python={{ cookiecutter.python_version }}
{% if cookiecutter.project_add_default_packages == "Yes"}
  - python-dotenv
  - scikit-learn
  - seaborn
  - statsmodels
  - tensorflow
{% endif %}
  - pip:
    {% if cookiecutter.project_add_default_packages == "Yes"}
    - h2o
    {% endif %}
    - pyhere